![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [3]:
import numpy as np
np.__version__

'2.1.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [72]:
my_array = np.arange(0,10,1)

my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [25]:
array = np.full((3,3), True)
print(array)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [41]:
my_array 
impar = []

for num in my_array:
    if num % 2 != 0:
        impar.append(num)

print(impar)


[1, 3, 5, 7, 9]


In [76]:
# Otra manera de sacar los impares
my_array[1::2]

array([1, 3, 5, 7, 9])

In [78]:
# Cuales son los elementos impares de my_array
mask = my_array %2 !=0
my_array[mask]

array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [46]:
my_array = [1,2,3,4,5,6,7,8,9] 
new_array = []

for num in my_array:
    if num % 2 != 0:
        new_array.append(-1)
    else:
        new_array.append(num)

print(new_array)

[-1, 2, -1, 4, -1, 6, -1, 8, -1]


In [79]:
# Otra manera de sustituir los impares.
my_array[1::2] = -1
my_array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [81]:
my_array.mean()

np.float64(1.5)

In [82]:
np.where(my_array % 2 != 0, -1, my_array)


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [88]:
my_array.reshape(1,-1)


array([[ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1]])

## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [95]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concat([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [96]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.concat([a,b], axis=0)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [98]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [129]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [103]:
my_array_10 = my_array*10
my_array[0]
my_array[-1]
my_array_10[1:8]

array([-10,  20, -10,  40, -10,  60, -10])

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [104]:
my_matrix = np.full((3,3))

TypeError: full() missing 1 required positional argument: 'fill_value'

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [105]:
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [107]:
np.arange(4,1,-0.25)

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [132]:
pip --version

pip 22.3.1 from /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pip (python 3.11)
Note: you may need to restart the kernel to use updated packages.


In [133]:
pip install matplotlib

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 14.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 266.4/266.4 kB 12.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 16.8 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 5.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 12.2 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.9/106.9 kB 11.9 MB/s eta 0:00:00

[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: pip3.11 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [137]:
import matplotlib.pyplot as plt

imagen = plt.imread("././img/numpy.png")
print(type(imagen))
print(imagen.shape)

plt.imshow(imagen)


FileNotFoundError: [Errno 2] No such file or directory: '././img/numpy.png'

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [128]:
np.full((4,1), "Pepe").reshape(2,2)

array([['Pepe', 'Pepe'],
       ['Pepe', 'Pepe']], dtype='<U4')

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [113]:
np.random.rand(4,5,3)

array([[[0.37068111, 0.53909132, 0.22094259],
        [0.23573242, 0.35536036, 0.00713273],
        [0.651597  , 0.11472148, 0.4404377 ],
        [0.264703  , 0.27680948, 0.02729083],
        [0.06692295, 0.97861626, 0.32030636]],

       [[0.56896592, 0.67134944, 0.55418072],
        [0.34362437, 0.71243523, 0.18876644],
        [0.98314838, 0.89297971, 0.20172919],
        [0.09470635, 0.8875116 , 0.79695309],
        [0.7204752 , 0.67381072, 0.22049587]],

       [[0.0410446 , 0.31290923, 0.96629053],
        [0.63827495, 0.07780389, 0.74783556],
        [0.05086348, 0.52583297, 0.23273983],
        [0.87096604, 0.89535335, 0.57777268],
        [0.56896168, 0.48083707, 0.79392656]],

       [[0.73939104, 0.79944421, 0.44355816],
        [0.87183072, 0.82840881, 0.32661787],
        [0.73791088, 0.51098543, 0.59009653],
        [0.10183508, 0.42180939, 0.81358171],
        [0.01002441, 0.353653  , 0.62249772]]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [118]:
np.full((10,1), False).reshape(2,-1)

array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [120]:
x =np.random.randint(10, 20, size = (5,2,6))

In [126]:
x.size


60

In [125]:
x.ndim

3

In [127]:
x.shape

(5, 2, 6)