![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [28]:
import numpy as np



In [241]:
my_array = np.arange(0,10,1)
my_array[::-2]


array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [242]:
my_array[7:9][::-1]


array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [243]:
my_array [0:3][::-1]


array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [245]:
m = np.arange(1, 21).reshape(4,5)
m[::-1, ::-1]


array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [246]:
m[:2, :2]


array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [247]:
m[::2, ::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [248]:
m[:3, ::-1]


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [212]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])

my_filter = ([True, False, False, True, False])

x[my_filter]

array(['Loro', 'Loro'], dtype='<U5')

In [249]:
x[x=="Loro"]

array(['Loro', 'Loro'], dtype='<U5')

In [250]:
np.where(x == 'Loro',"Loro", "No")


array(['Loro', 'No', 'No', 'Loro', 'No'], dtype='<U4')

In [251]:
np.extract(x=="Loro", x)

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [252]:
secuencia = np.arange(1,21).reshape(2,5,2)
secuencia


array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [253]:
m[::-1, ::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [256]:
a = np.full((10,),0)
a.itemsize

8

In [258]:
a[3] = 1
a

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [263]:
np.arange(9,50)[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [265]:
np.argwhere([1,2,0,0,4,0]).flatten()

array([0, 1, 4])

In [266]:
np.argwhere([1,2,0,0,4,0]).reshape(-1)

array([0, 1, 4])

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [270]:
np.random.rand(10,10)

array([[0.74493409, 0.06779736, 0.28722225, 0.61559616, 0.87773858,
        0.02906705, 0.33110271, 0.74268159, 0.69980807, 0.18088426],
       [0.30299874, 0.21789133, 0.00741401, 0.5820311 , 0.7813021 ,
        0.44793963, 0.60703719, 0.60328191, 0.95349956, 0.79292121],
       [0.42840542, 0.10055902, 0.25161332, 0.89766198, 0.59570559,
        0.28975672, 0.45488476, 0.25868127, 0.45909691, 0.58161664],
       [0.79382372, 0.84606154, 0.37615959, 0.6748167 , 0.75653715,
        0.85143785, 0.31508214, 0.92433502, 0.23662143, 0.83820713],
       [0.73681118, 0.44120158, 0.99851447, 0.5433585 , 0.16993433,
        0.03963249, 0.59487353, 0.56967816, 0.16045588, 0.11443774],
       [0.98451958, 0.14944942, 0.52620484, 0.01338507, 0.47030498,
        0.47090964, 0.62939192, 0.22058045, 0.33264647, 0.2383148 ],
       [0.59636429, 0.943213  , 0.30059812, 0.95889885, 0.4394577 ,
        0.29499281, 0.61393785, 0.21489758, 0.52546086, 0.5591678 ],
       [0.61128855, 0.75412837, 0.9751089

In [273]:
np.random.rand(10,10).max()


np.float64(0.9967876344519371)

In [274]:
np.random.rand(10,10).min()

np.float64(0.015550009185869462)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [280]:
np.random.randn(30).mean()

np.float64(-0.04283593009353413)

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [284]:
array = np.full((4,4),1)
array [1:-1, 1:-1]=0
array

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [289]:
a = np.full((8,8),1)
a[1::2, 1::2]=0



In [291]:
a[::2, ::2]=0
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [296]:
np.tile([[0,1],[1,0]], (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [297]:
m = np.random.randint(1, 10, (5,5))
media = m.mean()
std = m.std()

In [301]:
plt.hist(((m-media)/std).flatten());

NameError: name 'plt' is not defined

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [302]:
seq = np.arange(0,11)
seq

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [306]:
(3<=seq) & (seq<=8)

array([False, False, False,  True,  True,  True,  True,  True,  True,
       False, False])

In [308]:
seq[(3<=seq) & (seq<=8)]=-1
seq

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.